const plotdata = [
    { "Title": "Guardians of the Galaxy", "Genre": "Action", "Revenue (Millions)": 333.13, "Rating": 8.1 },
    { "Title": "Prometheus", "Genre": "Adventure", "Revenue (Millions)": 126.46, "Rating": 7 },
    { "Title": "Split", "Genre": "Horror", "Revenue (Millions)": 138.12, "Rating": 7.3 },
    { "Title": "Sing", "Genre": "Animation", "Revenue (Millions)": 270.32, "Rating": 7.2 },
    { "Title": "Suicide Squad", "Genre": "Action", "Revenue (Millions)": 325.02, "Rating": 6.2 },
    { "Title": "The Great Wall", "Genre": "Action", "Revenue (Millions)": 45.13, "Rating": 6.1 },
    { "Title": "La La Land", "Genre": "Comedy", "Revenue (Millions)": 151.06, "Rating": 8.3 },
    { "Title": "Mindhorn", "Genre": "Comedy", "Revenue (Millions)": null, "Rating": 6.4 },
    { "Title": "The Lost City of Z", "Genre": "Action", "Revenue (Millions)": 8.01, "Rating": 7.1 },
    { "Title": "Passengers", "Genre": "Adventure", "Revenue (Millions)": 100.01, "Rating": 7 },
    { "Title": "Fantastic Beasts and Where to Find Them", "Genre": "Adventure", "Revenue (Millions)": 234.02, "Rating": 7.5 },
    { "Title": "Hidden Figures", "Genre": "Other", "Revenue (Millions)": 169.27, "Rating": 7.8 },
    { "Title": "Rogue One", "Genre": "Action", "Revenue (Millions)": 532.17, "Rating": 7.9 },
    { "Title": "Moana", "Genre": "Animation", "Revenue (Millions)": 248.75, "Rating": 7.7 },
    { "Title": "Colossal", "Genre": "Action", "Revenue (Millions)": 2.87, "Rating": 6.4 },
    { "Title": "The Secret Life of Pets", "Genre": "Animation", "Revenue (Millions)": 368.31, "Rating": 6.6 },
    { "Title": "Hacksaw Ridge", "Genre": "Other", "Revenue (Millions)": 67.12, "Rating": 8.2 },
    { "Title": "Jason Bourne", "Genre": "Action", "Revenue (Millions)": 162.16, "Rating": 6.7 },
    { "Title": "Lion", "Genre": "Other", "Revenue (Millions)": 51.69, "Rating": 8.1 },
    { "Title": "Gold", "Genre": "Adventure", "Revenue (Millions)": 7.22, "Rating": 6.7 },
    { "Title": "Hounds of Love", "Genre": "Crime", "Revenue (Millions)": null, "Rating": 6.7 },
    { "Title": "Trolls", "Genre": "Animation", "Revenue (Millions)": 153.69, "Rating": 6.5 },
    { "Title": "Independence Day: Resurgence", "Genre": "Action", "Revenue (Millions)": 103.14, "Rating": 5.3 },
    { "Title": "Paris pieds nus", "Genre": "Comedy", "Revenue (Millions)": null, "Rating": 6.8 },
    { "Title": "Bahubali: The Beginning", "Genre": "Action", "Revenue (Millions)": 6.5, "Rating": 8.3 },
    { "Title": "Dead Awake", "Genre": "Horror", "Revenue (Millions)": 0.01, "Rating": 4.7 },
    { "Title": "Bad Moms", "Genre": "Comedy", "Revenue (Millions)": 113.08, "Rating": 6.2 },
    { "Title": "Assassin's Creed", "Genre": "Action", "Revenue (Millions)": 54.65, "Rating": 5.9 },
    { "Title": "Why Him?", "Genre": "Comedy", "Revenue (Millions)": 60.31, "Rating": 6.3 },
    { "Title": "X-Men: Apocalypse", "Genre": "Action", "Revenue (Millions)": 155.33, "Rating": 7.1 },
    { "Title": "Deadpool", "Genre": "Action", "Revenue (Millions)": 363.02, "Rating": 8 },
    { "Title": "Resident Evil: The Final Chapter", "Genre": "Action", "Revenue (Millions)": 26.84, "Rating": 5.6 },
    { "Title": "Captain America: Civil War", "Genre": "Action", "Revenue (Millions)": 408.08, "Rating": 7.9 },
    { "Title": "Interstellar", "Genre": "Adventure", "Revenue (Millions)": 187.99, "Rating": 8.6 },
    { "Title": "Doctor Strange", "Genre": "Action", "Revenue (Millions)": 232.6, "Rating": 7.6 },
    { "Title": "The Magnificent Seven", "Genre": "Action", "Revenue (Millions)": 93.38, "Rating": 6.9 },
    { "Title": "5- 25- 77", "Genre": "Comedy", "Revenue (Millions)": null, "Rating": 7.1 },
    { "Title": "Sausage Party", "Genre": "Animation", "Revenue (Millions)": 97.66, "Rating": 6.3 },
    { "Title": "Moonlight", "Genre": "Other", "Revenue (Millions)": 27.85, "Rating": 7.5 },
    { "Title": "Don't Fuck in the Woods", "Genre": "Horror", "Revenue (Millions)": null, "Rating": 2.7 },
    { "Title": "The Founder", "Genre": "Other", "Revenue (Millions)": 12.79, "Rating": 7.2 },
    { "Title": "Lowriders", "Genre": "Other", "Revenue (Millions)": 4.21, "Rating": 6.3 },
    { "Title": "Pirates of the Caribbean: On Stranger Tides", "Genre": "Action", "Revenue (Millions)": 241.06, "Rating": 6.7 },
    { "Title": "Miss Sloane", "Genre": "Other", "Revenue (Millions)": 3.44, "Rating": 7.3 },
    { "Title": "Gone Girl", "Genre": "Crime", "Revenue (Millions)": 167.74, "Rating": 8.1 },
    { "Title": "Live by Night", "Genre": "Crime", "Revenue (Millions)": 10.38, "Rating": 6.4 },
];

const scatterplotdata = [
    { "H/A": "A", "Team": "Torino", "xG conceded": 0.62, "Shot conceded": 10, "Result": "3" },
    { "H/A": "H", "Team": "Atalanta", "xG conceded": 2.35, "Shot conceded": 23, "Result": "1" },
    { "H/A": "A", "Team": "Milan", "xG conceded": 1.89, "Shot conceded": 26, "Result": "0" },
    { "H/A": "H", "Team": "Chievo", "xG conceded": 1.4, "Shot conceded": 13, "Result": "1" },
    { "H/A": "A", "Team": "Bologna", "xG conceded": 1.02, "Shot conceded": 11, "Result": 0 },
    { "H/A": "H", "Team": "Frosinone", "xG conceded": 0.56, "Shot conceded": 11, "Result": "3" },
    { "H/A": "H", "Team": "Lazio", "xG conceded": 1.01, "Shot conceded": 16, "Result": "3" },
    { "H/A": "A", "Team": "Empoli", "xG conceded": 1.56, "Shot conceded": 20, "Result": "3" },
    { "H/A": "H", "Team": "Spal", "xG conceded": 1.8, "Shot conceded": 6, "Result": "0" },
    { "H/A": "A", "Team": "Napoli", "xG conceded": 2.49, "Shot conceded": 26, "Result": "1" },
    { "H/A": "A", "Team": "Fiorentina", "xG conceded": 1.3, "Shot conceded": 14, "Result": "1" },
    { "H/A": "H", "Team": "Sampdoria", "xG conceded": 1.2, "Shot conceded": 8, "Result": "3" },
    { "H/A": "A", "Team": "Udinese", "xG conceded": 1.22, "Shot conceded": 9, "Result": "0" },
    { "H/A": "H", "Team": "Inter", "xG conceded": 2.68, "Shot conceded": 17, "Result": "1" },
    { "H/A": "A", "Team": "Cagliari", "xG conceded": 2.1, "Shot conceded": 16, "Result": "1" },
    { "H/A": "H", "Team": "Genoa", "xG conceded": 1.84, "Shot conceded": 15, "Result": "3" },
    { "H/A": "A", "Team": "Juventus", "xG conceded": 2.12, "Shot conceded": 20, "Result": "0" },
    { "H/A": "H", "Team": "Sassuolo", "xG conceded": 0.72, "Shot conceded": 10, "Result": "3" },
    { "H/A": "A", "Team": "Parma", "xG conceded": 0.58, "Shot conceded": 6, "Result": "3" },
    { "H/A": "H", "Team": "Torino", "xG conceded": 1.87, "Shot conceded": 10, "Result": "3" },
    { "H/A": "A", "Team": "Atalanta", "xG conceded": 2.68, "Shot conceded": 23, "Result": "1" },
    { "H/A": "H", "Team": "Milan", "xG conceded": 0.85, "Shot conceded": 8, "Result": "1" },
    { "H/A": "A", "Team": "Chievo", "xG conceded": 0.84, "Shot conceded": 16, "Result": "3" },
    { "H/A": "H", "Team": "Bologna", "xG conceded": 2.69, "Shot conceded": 20, "Result": "3" },
    { "H/A": "A", "Team": "Frosinone", "xG conceded": 1.51, "Shot conceded": 11, "Result": "3" },
    { "H/A": "A", "Team": "Lazio", "xG conceded": 1.77, "Shot conceded": 13, "Result": "0" },
    { "H/A": "H", "Team": "Empoli", "xG conceded": 0.14, "Shot conceded": 5, "Result": "3" },
    { "H/A": "A", "Team": "Real Madrid", "xG conceded": 3.58, "Shot conceded": 30, "Result": "0" },
    { "H/A": "H", "Team": "Viktoria Plzen", "xG conceded": 0.33, "Shot conceded": 7, "Result": 3 },
    { "H/A": "H", "Team": "CSKA Moscow", "xG conceded": 0.73, "Shot conceded": 13, "Result": "3" },
    { "H/A": "A", "Team": "CSKA Moscow", "xG conceded": 1.1, "Shot conceded": 14, "Result": "3" },
    { "H/A": "H", "Team": "Real Madrid", "xG conceded": 1.87, "Shot conceded": 12, "Result": "0" },
    { "H/A": "A", "Team": "Viktoria Plzen", "xG conceded": 1.85, "Shot conceded": 13, "Result": "0" },
    { "H/A": "A", "Team": "Porto", "xG conceded": 3.71, "Shot conceded": 31, "Result": "0" },
    { "H/A": "H", "Team": "Porto", "xG conceded": 0.56, "Shot conceded": 7, "Result": "3" }
]

export { plotdata, scatterplotdata }